### ISSUE TITLE
Unable to update multiselect option in D365 online

### ISSUE THREAD

**Issue by 23kiran** [Innofactor/XrmToolBox.BulkDataUpdater#30]
Getting an error when user tries to update Multi select optionset. Error is "Attribute of type Virtual is not currently support"

**Comment by rappen** [comment]
Of course! 
Thanks for the bump, I will make it happen.

**Comment by AngelRodriguez8008** [comment]
That's still does not work. Some progress or block?
![image](https://user-images.githubusercontent.com/27274469/114705629-377b1d00-9d28-11eb-9721-9195d321d4a8.png)

**Comment by rappen** [comment]
Nothing done yet, but I'm getting there! :)
