### ISSUE TITLE
FetchXml 

### ISSUE THREAD

**Issue by medevil84** [Innofactor/XrmToolBox.BulkDataUpdater#7]
"Use FetchXML Builder" is broken with the latest review.
Program versions:
XrmToolBox: v1.2017.1.11
FetchXML Builder: 1.2016.12.115
Bulk Data Updater: 1.2017.2.11
The problem seems to be related to the message passed to FetchXMLBuilder, if using type FXBMessageBusArgument instead of string, it works: https://github.com/medevil84/XrmToolBox.BulkDataUpdater/commit/65b6e55e83a57440a5cea1f4b368f4dc6d75322d 
@rappen let me know if i have to make a pull request for this changeset. I'm not using a reference to fetchxml builder instead i've included some code from it, so it can conflict somehow/somewhere.

**Comment by rappen** [comment]
I just tested with the exact same versions, and it works...
Could you try deleting all ``Cinteros.*`` files in the plugin folder?
You find them easiest by clicking Settings gear button, Paths, Open XrmToolBox storage folder, Plugins.
And then restart XTB and re-download from Plugins Store.

**Comment by rappen** [comment]
Allowing "simple" string argument was introduced back in June...
https://github.com/Innofactor/FetchXMLBuilder/commit/b9285ddd5472461dd1e91bf7a1821a206dccb835

**Comment by medevil84** [comment]
Hi @rappen still doesn't work...
Deleted the entire "mscrmtools" storage directory (found it in %APPDATA%), downloaded fresh copy of xrmtoolbox from website and installed only 3 plugins: "FetchXML Builder", "Bulk Data Updater" and "Export to Excel".
The FetchXML Builder plugins is correctlty opened by clicking on "Get Records", however, it doesn't enable the return to the caller button. It works correctly with the "Export to Excel" plugin.
Any other idea?
NOTE: I've cloned the repository and compiled the dll from the sources, but the behavior is exactly the same.

**Comment by rappen** [comment]
@medevil84 New version of FetchXML Builder is now available in the Plugins Store to handle this!
Problem was when FXB was called without any FetchXML to be initialized with.
Big thanks to @rajyraman for debugging!

**Comment by medevil84** [comment]
@rappen great, just updated the fxb plugin and confirmed it's working.
Just thinking, shouldn't we modify the bulk data updater plugin to call FXB with the current fetchxml? (even if it's null/empty)

**Comment by rappen** [comment]
It actually does, but running first time it has no previously stored fetch :)
